#!/bin/bash
# relies on following environment variables:
# $ES - absolute path to directory containing elasticsearch-6.2.1 folder

[ -z "$ES" ] && echo "Need to set ES" && exit 1;

cd $ES
if [ $1 != "clean" ]; then
rm -rf machines
mkdir machines
cd machines
for i in `seq $1 $2`;
do
        mkdir $i
        printf "$i\n" >> machine_list.txt
        cd $i
        cp -r $ES/elasticsearch-6.2.1 .
        echo "node.name: 127x$i" >> elasticsearch-6.2.1/config/elasticsearch.yml
        echo "path.logs: $ES/machines/$i/logs" >> elasticsearch-6.2.1/config/elasticsearch.yml
        echo "path.data: $ES/machines/$i/data" >> elasticsearch-6.2.1/config/elasticsearch.yml
        let "ip=i+10"
        echo "network.host: 129.65.221.$ip" >> elasticsearch-6.2.1/config/elasticsearch.yml
        if [ $i == 26 ]; then
                echo 'discovery.zen.ping.unicast.hosts: ["129.65.221.37", "129.65.221.38"]' >> elasticsearch-6.2.1/config/elasticsearch.yml
        elif [ $i == 27 ]; then
                echo 'discovery.zen.ping.unicast.hosts: ["129.65.221.36", "129.65.221.38"]' >> elasticsearch-6.2.1/config/elasticsearch.yml
        elif [ $i == 28 ]; then
                echo 'discovery.zen.ping.unicast.hosts: ["129.65.221.37", "129.65.221.36"]' >> elasticsearch-6.2.1/config/elasticsearch.yml
        fi
        echo "discovery.zen.minimum_master_nodes: 2" >> elasticsearch-6.2.1/config/elasticsearch.yml
        #echo "http.port: 9200" >> elasticsearch-6.2.1/config/elasticsearch.yml
        nohup ssh 127x${i}.csc.calpoly.edu "$ES/machines/$i/elasticsearch-6.2.1/bin/elasticsearch" &> out.txt < /dev/null &
        cd ..
done
cd ..
else
cat machines/machine_list.txt | while read line
do
        pid=`nohup ssh 127x${line}.csc.calpoly.edu "ps -ef | grep /bin/java | grep $USER | grep elasticsearch"  < /dev/null &`
        pid=`echo $pid | awk -F'[: ]+' '{ print $2 }'`

        for i in $pid;
        do
                nohup ssh 127x${line}.csc.calpoly.edu "kill -9 $i" &> /dev/null < /dev/null &
        done
done
rm -rf machines
fi